# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f471a8e77b19b6b28ec203f205cf3287232bf1b657d5281cf0da2f823df4a72d946581da6aa8c2e756afde4ca75df7aff0e1df4eb359c17f5ac65d80d043bcf

test:
  secret_key_base: c00c823ada31ccb3878281c40c92737ceb2d9538335234770682e90e946e1fd744e52d9cb05ad9498b4d027578cbec6a94c05351c9db01ef124853b2adf85c02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
